# Generated by Django 4.0.4 on 2022-05-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_email_remove_user_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
